"""Curated ayah pool — 20+ authentic Quranic verses for each emotion, daily reminders, and complete Adhkar (Hisn al-Muslim)."""

EMOTION_LABELS = {
    "sad":         {"en": "Sad",         "ar": "حزين"},
    "anxious":     {"en": "Anxious",     "ar": "قلق"},
    "angry":       {"en": "Angry",       "ar": "غاضب"},
    "exhausted":   {"en": "Exhausted",   "ar": "متعب"},
    "grateful":    {"en": "Grateful",    "ar": "ممتن"},
    "hopeless":    {"en": "Hopeless",    "ar": "يائس"},
    "happy":       {"en": "Happy",       "ar": "سعيد"},
    "restless":    {"en": "Restless",    "ar": "مضطرب"},
    "heartbroken": {"en": "Heartbroken", "ar": "محطم"},
    "lonely":      {"en": "Lonely",      "ar": "وحيد"},
}

EMOTION_AYAH_POOL = {
    "sad": [
        ("وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَى", "And your Lord is going to give you, and you will be satisfied.", "Ad-Duha", "93:5"),
        ("مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ", "Your Lord has not abandoned you, nor has He detested you.", "Ad-Duha", "93:3"),
        ("فَإِنَّ مَعَ الْعُسْرِ يُسْرًا", "For indeed, with hardship will be ease.", "Al-Inshirah", "94:5"),
        ("إِنَّ مَعَ الْعُسْرِ يُسْرًا", "Indeed, with hardship will be ease.", "Al-Inshirah", "94:6"),
        ("أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ", "Have We not expanded for you your breast?", "Al-Inshirah", "94:1"),
        ("إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ", "I only complain of my suffering and grief to Allah.", "Yusuf", "12:86"),
        ("لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا", "Do not grieve. Indeed, Allah is with us.", "At-Tawbah", "9:40"),
        ("إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", "Indeed, Allah is with the patient.", "Al-Baqarah", "2:153"),
        ("وَبَشِّرِ الصَّابِرِينَ", "And give good tidings to the patient.", "Al-Baqarah", "2:155"),
        ("وَلَنَبْلُوَنَّكُم بِشَيْءٍ مِّنَ الْخَوْفِ وَالْجُوعِ", "And We will surely test you with something of fear and hunger…", "Al-Baqarah", "2:155"),
        ("الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ", "Who, when disaster strikes, say: Indeed we belong to Allah and to Him we shall return.", "Al-Baqarah", "2:156"),
        ("وَالصَّابِرِينَ فِي الْبَأْسَاءِ وَالضَّرَّاءِ", "Those patient in poverty, hardship, and at the time of fierce battle.", "Al-Baqarah", "2:177"),
        ("فَاصْبِرْ صَبْرًا جَمِيلًا", "So be patient with a beautiful patience.", "Al-Ma'arij", "70:5"),
        ("وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ", "Seek help through patience and prayer.", "Al-Baqarah", "2:45"),
        ("سَيَجْعَلُ اللَّهُ بَعْدَ عُسْرٍ يُسْرًا", "Allah will bring about, after hardship, ease.", "At-Talaq", "65:7"),
        ("إِنَّ رَحْمَتَ اللَّهِ قَرِيبٌ مِّنَ الْمُحْسِنِينَ", "Indeed, the mercy of Allah is near to the doers of good.", "Al-A'raf", "7:56"),
        ("وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ", "Do not despair of relief from Allah.", "Yusuf", "12:87"),
        ("وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ", "And He is with you wherever you are.", "Al-Hadid", "57:4"),
        ("أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ", "Verily, in the remembrance of Allah do hearts find rest.", "Ar-Ra'd", "13:28"),
        ("وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ", "And We are closer to him than his jugular vein.", "Qaf", "50:16"),
        ("إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ كَانَتْ لَهُمْ جَنَّاتُ الْفِرْدَوْسِ نُزُلًا", "Indeed, those who have believed and done righteous deeds — they will have the Gardens of Paradise as a refuge.", "Al-Kahf", "18:107"),
    ],

    "anxious": [
        ("أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ", "Verily, in the remembrance of Allah do hearts find rest.", "Ar-Ra'd", "13:28"),
        ("هُوَ الَّذِي أَنزَلَ السَّكِينَةَ فِي قُلُوبِ الْمُؤْمِنِينَ", "It is He who sent down tranquility into the hearts of the believers.", "Al-Fath", "48:4"),
        ("لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", "Allah does not burden a soul beyond that it can bear.", "Al-Baqarah", "2:286"),
        ("وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ", "Whoever relies upon Allah — then He is sufficient for him.", "At-Talaq", "65:3"),
        ("وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا", "Whoever fears Allah, He will make for him a way out.", "At-Talaq", "65:2"),
        ("وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ", "And He will provide for him from where he does not expect.", "At-Talaq", "65:3"),
        ("حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", "Sufficient for us is Allah, and the best Disposer of affairs.", "Al-Imran", "3:173"),
        ("فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ", "And once you have decided, then place your trust in Allah.", "Al-Imran", "3:159"),
        ("لَا تَخَفْ وَلَا تَحْزَنْ ۚ إِنَّا مُنَجُّوكَ", "Do not fear and do not grieve. Indeed, We are going to save you.", "Al-Ankabut", "29:33"),
        ("لَا تَخَفْ ۖ إِنَّكَ أَنتَ الْأَعْلَىٰ", "Do not fear. Indeed, you are the superior.", "Ta-Ha", "20:68"),
        ("إِنَّ اللَّهَ مَعَ الَّذِينَ اتَّقَوا وَّالَّذِينَ هُم مُّحْسِنُونَ", "Indeed, Allah is with those who fear Him and those who do good.", "An-Nahl", "16:128"),
        ("وَكَانَ حَقًّا عَلَيْنَا نَصْرُ الْمُؤْمِنِينَ", "And it was incumbent upon Us to support the believers.", "Ar-Rum", "30:47"),
        ("وَإِن يَمْسَسْكَ اللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ إِلَّا هُوَ", "If Allah touches you with adversity, none can remove it but Him.", "Al-An'am", "6:17"),
        ("قُلْ لَّن يُصِيبَنَا إِلَّا مَا كَتَبَ اللَّهُ لَنَا", "Say: nothing will happen to us except what Allah has decreed for us.", "At-Tawbah", "9:51"),
        ("وَمَا تَوْفِيقِي إِلَّا بِاللَّهِ ۚ عَلَيْهِ تَوَكَّلْتُ", "My success is only by Allah. Upon Him I have relied.", "Hud", "11:88"),
        ("وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ", "When My servants ask you concerning Me — indeed, I am near.", "Al-Baqarah", "2:186"),
        ("وَاللَّهُ يَعْلَمُ مَا فِي قُلُوبِكُمْ", "And Allah knows what is in your hearts.", "Al-Ahzab", "33:51"),
        ("أَوْفُوا بِعَهْدِي أُوفِ بِعَهْدِكُمْ وَإِيَّايَ فَارْهَبُونِ", "Fulfill My covenant — I will fulfill yours; and fear only Me.", "Al-Baqarah", "2:40"),
        ("أَلَيْسَ اللَّهُ بِكَافٍ عَبْدَهُ", "Is not Allah sufficient for His servant?", "Az-Zumar", "39:36"),
        ("فَاللَّهُ خَيْرٌ حَافِظًا ۖ وَهُوَ أَرْحَمُ الرَّاحِمِينَ", "Allah is the best guardian, and He is the Most Merciful of the merciful.", "Yusuf", "12:64"),
        ("إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ", "Indeed, with me is my Lord — He will guide me.", "Ash-Shu'ara", "26:62"),
    ],

    "angry": [
        ("وَالْكَاظِمِينَ الْغَيْظَ وَالْعَافِينَ عَنِ النَّاسِ", "Those who restrain anger and pardon people — Allah loves the doers of good.", "Al-Imran", "3:134"),
        ("ادْفَعْ بِالَّتِي هِيَ أَحْسَنُ", "Repel evil with that which is better.", "Fussilat", "41:34"),
        ("فَإِذَا الَّذِي بَيْنَكَ وَبَيْنَهُ عَدَاوَةٌ كَأَنَّهُ وَلِيٌّ حَمِيمٌ", "Then suddenly the one between whom and you was enmity becomes as a devoted friend.", "Fussilat", "41:34"),
        ("وَإِن تَعْفُوا وَتَصْفَحُوا وَتَغْفِرُوا فَإِنَّ اللَّهَ غَفُورٌ رَّحِيمٌ", "If you pardon, overlook, and forgive — indeed, Allah is Forgiving and Merciful.", "At-Taghabun", "64:14"),
        ("وَلَمَن صَبَرَ وَغَفَرَ إِنَّ ذَٰلِكَ لَمِنْ عَزْمِ الْأُمُورِ", "Whoever is patient and forgives — that is of the matters of resolve.", "Ash-Shura", "42:43"),
        ("خُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ وَأَعْرِضْ عَنِ الْجَاهِلِينَ", "Take what is given freely, enjoin good, and turn away from the ignorant.", "Al-A'raf", "7:199"),
        ("وَجَزَاءُ سَيِّئَةٍ سَيِّئَةٌ مِّثْلُهَا ۖ فَمَنْ عَفَا وَأَصْلَحَ فَأَجْرُهُ عَلَى اللَّهِ", "The repayment of a bad deed is one like it. But whoever pardons and reconciles — his reward is with Allah.", "Ash-Shura", "42:40"),
        ("وَإِذَا خَاطَبَهُمُ الْجَاهِلُونَ قَالُوا سَلَامًا", "When the ignorant address them, they say: Peace.", "Al-Furqan", "25:63"),
        ("وَلَا تَسْتَوِي الْحَسَنَةُ وَلَا السَّيِّئَةُ", "Good and evil are not equal.", "Fussilat", "41:34"),
        ("وَقُل لِّعِبَادِي يَقُولُوا الَّتِي هِيَ أَحْسَنُ", "Tell My servants to say that which is best.", "Al-Isra", "17:53"),
        ("إِنَّ الشَّيْطَانَ يَنزَغُ بَيْنَهُمْ", "Indeed, Satan sows discord among them.", "Al-Isra", "17:53"),
        ("فَاسْتَعِذْ بِاللَّهِ ۖ إِنَّهُ هُوَ السَّمِيعُ الْعَلِيمُ", "Seek refuge in Allah — He is the Hearing, the Knowing.", "Fussilat", "41:36"),
        ("وَإِذَا مَرُّوا بِاللَّغْوِ مَرُّوا كِرَامًا", "When they pass by ill speech, they pass by with dignity.", "Al-Furqan", "25:72"),
        ("لَا يَنْهَاكُمُ اللَّهُ عَنِ الَّذِينَ لَمْ يُقَاتِلُوكُمْ فِي الدِّينِ … أَن تَبَرُّوهُمْ وَتُقْسِطُوا إِلَيْهِمْ", "Allah does not forbid you from being kind and just to those who have not fought you.", "Al-Mumtahanah", "60:8"),
        ("إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ", "Allah commands justice, good conduct, and giving to relatives.", "An-Nahl", "16:90"),
        ("وَلَا تَجْعَلْ يَدَكَ مَغْلُولَةً إِلَىٰ عُنُقِكَ", "Do not make your hand chained to your neck.", "Al-Isra", "17:29"),
        ("وَجَاهِدْهُم بِهِ جِهَادًا كَبِيرًا", "Strive against them with the Qur'an a great striving.", "Al-Furqan", "25:52"),
        ("وَلَا تَسُبُّوا الَّذِينَ يَدْعُونَ مِن دُونِ اللَّهِ", "Do not insult those they invoke other than Allah.", "Al-An'am", "6:108"),
        ("وَقُولُوا لِلنَّاسِ حُسْنًا", "Speak to people good words.", "Al-Baqarah", "2:83"),
        ("سَلَامٌ عَلَيْكُمْ لَا نَبْتَغِي الْجَاهِلِينَ", "Peace be upon you — we seek not the ignorant.", "Al-Qasas", "28:55"),
    ],

    "exhausted": [
        ("فَإِنَّ مَعَ الْعُسْرِ يُسْرًا ۞ إِنَّ مَعَ الْعُسْرِ يُسْرًا", "For with hardship will be ease. Indeed, with hardship will be ease.", "Al-Inshirah", "94:5-6"),
        ("لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", "Allah does not burden a soul beyond that it can bear.", "Al-Baqarah", "2:286"),
        ("إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ", "Indeed, with me is my Lord — He will guide me.", "Ash-Shu'ara", "26:62"),
        ("وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا", "We made your sleep for rest.", "An-Naba", "78:9"),
        ("وَجَعَلْنَا اللَّيْلَ لِبَاسًا ۞ وَجَعَلْنَا النَّهَارَ مَعَاشًا", "We made the night a covering, and the day for livelihood.", "An-Naba", "78:10-11"),
        ("هُوَ الَّذِي جَعَلَ لَكُمُ اللَّيْلَ لِتَسْكُنُوا فِيهِ", "It is He who made for you the night that you may rest in it.", "Yunus", "10:67"),
        ("يُرِيدُ اللَّهُ بِكُمُ الْيُسْرَ وَلَا يُرِيدُ بِكُمُ الْعُسْرَ", "Allah intends for you ease and does not intend hardship for you.", "Al-Baqarah", "2:185"),
        ("وَمَا جَعَلَ عَلَيْكُمْ فِي الدِّينِ مِنْ حَرَجٍ", "He has not placed upon you in religion any difficulty.", "Al-Hajj", "22:78"),
        ("وَهُوَ الَّذِي يَقْبَلُ التَّوْبَةَ عَنْ عِبَادِهِ", "It is He who accepts repentance from His servants.", "Ash-Shura", "42:25"),
        ("سَنُيَسِّرُكَ لِلْيُسْرَىٰ", "We will ease you toward ease.", "Al-A'la", "87:8"),
        ("وَلَا تَقْعُدُوا كُلَّ مَقْعَدٍ ۚ وَاذْكُرُوا اللَّهَ كَثِيرًا", "Remember Allah often.", "Al-Anfal", "8:45"),
        ("وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ", "Seek help through patience and prayer.", "Al-Baqarah", "2:45"),
        ("يَا أَيُّهَا الْإِنسَانُ إِنَّكَ كَادِحٌ إِلَىٰ رَبِّكَ كَدْحًا فَمُلَاقِيهِ", "O mankind, you are laboring toward your Lord, and you will meet Him.", "Al-Inshiqaq", "84:6"),
        ("الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ اللَّهِ", "Those who believe — their hearts find rest in the remembrance of Allah.", "Ar-Ra'd", "13:28"),
        ("وَعَدَ اللَّهُ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ ۙ لَهُم مَّغْفِرَةٌ وَأَجْرٌ عَظِيمٌ", "Allah has promised those who believe and do righteous deeds — for them is forgiveness and a great reward.", "Al-Ma'idah", "5:9"),
        ("فَاسْتَقِمْ كَمَا أُمِرْتَ", "Stand firm as you have been commanded.", "Hud", "11:112"),
        ("إِنَّ الَّذِينَ قَالُوا رَبُّنَا اللَّهُ ثُمَّ اسْتَقَامُوا تَتَنَزَّلُ عَلَيْهِمُ الْمَلَائِكَةُ", "Those who say: our Lord is Allah, and then remain upon a straight course — the angels descend upon them.", "Fussilat", "41:30"),
        ("أَلَا تَخَافُوا وَلَا تَحْزَنُوا وَأَبْشِرُوا بِالْجَنَّةِ", "Do not fear, do not grieve, but receive good tidings of Paradise.", "Fussilat", "41:30"),
        ("اللَّهُ لَطِيفٌ بِعِبَادِهِ يَرْزُقُ مَن يَشَاءُ", "Allah is most subtle with His servants — He provides for whom He wills.", "Ash-Shura", "42:19"),
        ("وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا", "Those who strive for Us — We will surely guide them to Our ways.", "Al-Ankabut", "29:69"),
    ],

    "grateful": [
        ("لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", "If you are grateful, I will surely increase you.", "Ibrahim", "14:7"),
        ("وَإِن تَعُدُّوا نِعْمَةَ اللَّهِ لَا تُحْصُوهَا", "If you should count the favors of Allah, you could not enumerate them.", "An-Nahl", "16:18"),
        ("وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ", "Be grateful to Me and do not disbelieve in Me.", "Al-Baqarah", "2:152"),
        ("فَاذْكُرُونِي أَذْكُرْكُمْ", "So remember Me — I will remember you.", "Al-Baqarah", "2:152"),
        ("وَكُلُوا مِمَّا رَزَقَكُمُ اللَّهُ", "Eat of what Allah has provided for you.", "Al-Ma'idah", "5:88"),
        ("وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ", "And as for the favor of your Lord — proclaim it.", "Ad-Duha", "93:11"),
        ("الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", "All praise is to Allah, Lord of the worlds.", "Al-Fatihah", "1:2"),
        ("وَهُوَ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ بِالْحَقِّ", "It is He who created the heavens and the earth in truth.", "Al-An'am", "6:73"),
        ("الَّذِي خَلَقَ الْمَوْتَ وَالْحَيَاةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا", "He created death and life to test which of you is best in deed.", "Al-Mulk", "67:2"),
        ("هُوَ الَّذِي جَعَلَ لَكُمُ الْأَرْضَ ذَلُولًا", "It is He who made the earth tame for you.", "Al-Mulk", "67:15"),
        ("وَسَخَّرَ لَكُم مَّا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ", "He has subjected to you what is in the heavens and earth.", "Al-Jathiya", "45:13"),
        ("وَآتَاكُم مِّن كُلِّ مَا سَأَلْتُمُوهُ", "He has given you from all you have asked of Him.", "Ibrahim", "14:34"),
        ("وَفِي السَّمَاءِ رِزْقُكُمْ وَمَا تُوعَدُونَ", "In the heaven is your provision and whatever you are promised.", "Adh-Dhariyat", "51:22"),
        ("فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ", "So which of the favors of your Lord would you deny?", "Ar-Rahman", "55:13"),
        ("وَإِنَّ رَبَّكَ لَذُو فَضْلٍ عَلَى النَّاسِ", "Indeed, your Lord is full of bounty for the people.", "An-Naml", "27:73"),
        ("هَذَا مِن فَضْلِ رَبِّي", "This is from the favor of my Lord.", "An-Naml", "27:40"),
        ("رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ", "My Lord, enable me to be grateful for Your favor.", "An-Naml", "27:19"),
        ("وَقَلِيلٌ مِّنْ عِبَادِيَ الشَّكُورُ", "And few of My servants are grateful.", "Saba", "34:13"),
        ("اعْمَلُوا آلَ دَاوُودَ شُكْرًا", "Work, O family of David, in gratitude.", "Saba", "34:13"),
        ("وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ ۚ وَاللَّهُ بِمَا تَعْمَلُونَ بَصِيرٌ", "He is with you wherever you are, and Allah sees what you do.", "Al-Hadid", "57:4"),
        ("الْحَمْدُ لِلَّهِ الَّذِي هَدَانَا لِهَٰذَا", "Praise be to Allah, who has guided us to this.", "Al-A'raf", "7:43"),
    ],

    "hopeless": [
        ("لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ", "Do not despair of the mercy of Allah.", "Az-Zumar", "39:53"),
        ("إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا", "Indeed, Allah forgives all sins.", "Az-Zumar", "39:53"),
        ("وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ ۖ إِنَّهُ لَا يَيْأَسُ مِن رَّوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ", "Do not despair of relief from Allah. Only the disbelieving people despair.", "Yusuf", "12:87"),
        ("وَمَن يَقْنَطُ مِن رَّحْمَةِ رَبِّهِ إِلَّا الضَّالُّونَ", "Who despairs of his Lord's mercy except those astray?", "Al-Hijr", "15:56"),
        ("إِنَّ رَحْمَتَ اللَّهِ قَرِيبٌ مِّنَ الْمُحْسِنِينَ", "The mercy of Allah is near to the doers of good.", "Al-A'raf", "7:56"),
        ("وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ", "My mercy encompasses all things.", "Al-A'raf", "7:156"),
        ("يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ لَا تَقْنَطُوا", "O My servants who have transgressed against themselves — do not despair.", "Az-Zumar", "39:53"),
        ("سَيَجْعَلُ اللَّهُ بَعْدَ عُسْرٍ يُسْرًا", "Allah will bring, after hardship, ease.", "At-Talaq", "65:7"),
        ("وَهُوَ الَّذِي يَقْبَلُ التَّوْبَةَ عَنْ عِبَادِهِ", "It is He who accepts repentance from His servants.", "Ash-Shura", "42:25"),
        ("إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ", "Allah loves those who repent and those who purify themselves.", "Al-Baqarah", "2:222"),
        ("وَمَن يَعْمَلْ سُوءًا أَوْ يَظْلِمْ نَفْسَهُ ثُمَّ يَسْتَغْفِرِ اللَّهَ يَجِدِ اللَّهَ غَفُورًا رَّحِيمًا", "Whoever does evil or wrongs himself then seeks Allah's forgiveness will find Allah Forgiving, Merciful.", "An-Nisa", "4:110"),
        ("وَاللَّهُ يُرِيدُ أَن يَتُوبَ عَلَيْكُمْ", "Allah wants to accept your repentance.", "An-Nisa", "4:27"),
        ("نَبِّئْ عِبَادِي أَنِّي أَنَا الْغَفُورُ الرَّحِيمُ", "Inform My servants that it is I who am the Forgiving, the Merciful.", "Al-Hijr", "15:49"),
        ("غَافِرِ الذَّنبِ وَقَابِلِ التَّوْبِ", "The Forgiver of sin, the Acceptor of repentance.", "Ghafir", "40:3"),
        ("وَهُوَ الْغَفُورُ الْوَدُودُ", "He is the Forgiving, the Affectionate.", "Al-Buruj", "85:14"),
        ("وَكَانَ بِالْمُؤْمِنِينَ رَحِيمًا", "He is, to the believers, Merciful.", "Al-Ahzab", "33:43"),
        ("وَمَا قَدَرُوا اللَّهَ حَقَّ قَدْرِهِ", "They have not appraised Allah with His true appraisal.", "Al-An'am", "6:91"),
        ("إِنَّ بَطْشَ رَبِّكَ لَشَدِيدٌ ۞ إِنَّهُ هُوَ يُبْدِئُ وَيُعِيدُ ۞ وَهُوَ الْغَفُورُ الْوَدُودُ", "The grip of your Lord is severe. He originates and restores — and He is the Forgiving, the Affectionate.", "Al-Buruj", "85:12-14"),
        ("قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ", "Say: O My servants who have transgressed against themselves…", "Az-Zumar", "39:53"),
        ("وَأَن تَوْبَتُهُ سَوْفَ تَكُونُ", "Repentance with Allah is only for those who do wrong in ignorance.", "An-Nisa", "4:17"),
        ("وَاللَّهُ غَفُورٌ رَّحِيمٌ", "And Allah is Forgiving, Merciful.", "Al-Baqarah", "2:173"),
    ],

    "happy": [
        ("وَإِن تَعُدُّوا نِعْمَةَ اللَّهِ لَا تُحْصُوهَا", "If you should count the favors of Allah, you could not enumerate them.", "An-Nahl", "16:18"),
        ("الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ اللَّهِ", "Those who believe — their hearts find rest in the remembrance of Allah.", "Ar-Ra'd", "13:28"),
        ("قُلْ بِفَضْلِ اللَّهِ وَبِرَحْمَتِهِ فَبِذَٰلِكَ فَلْيَفْرَحُوا", "Say: in the bounty of Allah and in His mercy — in that let them rejoice.", "Yunus", "10:58"),
        ("هُوَ خَيْرٌ مِّمَّا يَجْمَعُونَ", "It is better than what they accumulate.", "Yunus", "10:58"),
        ("لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", "If you are grateful, I will surely increase you.", "Ibrahim", "14:7"),
        ("وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ", "As for the favor of your Lord — proclaim it.", "Ad-Duha", "93:11"),
        ("الْيَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ", "This day I have perfected for you your religion.", "Al-Ma'idah", "5:3"),
        ("وَأَتْمَمْتُ عَلَيْكُمْ نِعْمَتِي", "And completed My favor upon you.", "Al-Ma'idah", "5:3"),
        ("رَضِيتُ لَكُمُ الْإِسْلَامَ دِينًا", "I have approved Islam for you as a religion.", "Al-Ma'idah", "5:3"),
        ("وَرَضُوا عَنْهُ ۚ ذَٰلِكَ لِمَنْ خَشِيَ رَبَّهُ", "They are pleased with Him — that is for whoever has feared his Lord.", "Al-Bayyinah", "98:8"),
        ("لَهُمْ مَا يَشَاءُونَ فِيهَا وَلَدَيْنَا مَزِيدٌ", "They will have whatever they wish therein, and with Us is more.", "Qaf", "50:35"),
        ("سَلَامٌ عَلَيْكُمْ بِمَا صَبَرْتُمْ", "Peace be upon you for what you patiently endured.", "Ar-Ra'd", "13:24"),
        ("وَيُنَجِّي اللَّهُ الَّذِينَ اتَّقَوْا بِمَفَازَتِهِمْ", "Allah will save those who feared Him by their attainment.", "Az-Zumar", "39:61"),
        ("فَاذْكُرُوا اللَّهَ كَذِكْرِكُمْ آبَاءَكُمْ أَوْ أَشَدَّ ذِكْرًا", "Remember Allah as you remember your forefathers, or with even greater remembrance.", "Al-Baqarah", "2:200"),
        ("وَأَنَّ هَٰذَا صِرَاطِي مُسْتَقِيمًا فَاتَّبِعُوهُ", "This is My straight path, so follow it.", "Al-An'am", "6:153"),
        ("فِيهَا مَا تَشْتَهِيهِ الْأَنفُسُ وَتَلَذُّ الْأَعْيُنُ", "Therein is whatever the souls desire and eyes delight in.", "Az-Zukhruf", "43:71"),
        ("جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ", "Gardens beneath which rivers flow.", "Al-Baqarah", "2:25"),
        ("سَلَامٌ قَوْلًا مِّن رَّبٍّ رَّحِيمٍ", "Peace, a word from a Merciful Lord.", "Ya-Sin", "36:58"),
        ("وَالَّذِينَ آمَنُوا أَشَدُّ حُبًّا لِّلَّهِ", "Those who believe are stronger in love for Allah.", "Al-Baqarah", "2:165"),
        ("إِنَّ هَٰذَا لَهُوَ الْفَوْزُ الْعَظِيمُ", "Indeed, this is the great attainment.", "As-Saffat", "37:60"),
        ("وَالْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", "And praise belongs to Allah, Lord of the worlds.", "As-Saffat", "37:182"),
    ],

    "restless": [
        ("لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", "Allah does not burden a soul beyond that it can bear.", "Al-Baqarah", "2:286"),
        ("وَنُنَزِّلُ مِنَ الْقُرْآنِ مَا هُوَ شِفَاءٌ وَرَحْمَةٌ لِّلْمُؤْمِنِينَ", "We send down of the Qur'an that which is healing and mercy for the believers.", "Al-Isra", "17:82"),
        ("وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ وَإِنَّهَا لَكَبِيرَةٌ", "Seek help through patience and prayer — indeed, it is difficult except for the humbly submissive.", "Al-Baqarah", "2:45"),
        ("وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ ۖ أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ", "When My servants ask you about Me — I am near. I respond to the supplicant when he calls upon Me.", "Al-Baqarah", "2:186"),
        ("هُوَ الَّذِي أَنزَلَ السَّكِينَةَ", "It is He who sent down tranquility.", "Al-Fath", "48:4"),
        ("فَفِرُّوا إِلَى اللَّهِ", "So flee to Allah.", "Adh-Dhariyat", "51:50"),
        ("وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ إِلَّا لِيَعْبُدُونِ", "I did not create jinn and mankind except to worship Me.", "Adh-Dhariyat", "51:56"),
        ("إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ", "Indeed, with me is my Lord — He will guide me.", "Ash-Shu'ara", "26:62"),
        ("قُل لَّن يُصِيبَنَا إِلَّا مَا كَتَبَ اللَّهُ لَنَا", "Say: nothing will happen to us except what Allah has decreed for us.", "At-Tawbah", "9:51"),
        ("وَعَلَى اللَّهِ فَتَوَكَّلُوا إِن كُنتُم مُّؤْمِنِينَ", "And upon Allah rely, if you should be believers.", "Al-Ma'idah", "5:23"),
        ("وَاللَّهُ خَيْرُ الْمَاكِرِينَ", "Allah is the best of planners.", "Al-Imran", "3:54"),
        ("وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ", "Perhaps you dislike a thing and it is good for you.", "Al-Baqarah", "2:216"),
        ("وَاللَّهُ يَعْلَمُ وَأَنتُمْ لَا تَعْلَمُونَ", "Allah knows, and you do not know.", "Al-Baqarah", "2:216"),
        ("ادْعُونِي أَسْتَجِبْ لَكُمْ", "Call upon Me — I will respond to you.", "Ghafir", "40:60"),
        ("وَمَا مِن دَابَّةٍ فِي الْأَرْضِ إِلَّا عَلَى اللَّهِ رِزْقُهَا", "There is no creature on earth but that upon Allah is its provision.", "Hud", "11:6"),
        ("وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ", "Whoever relies on Allah — He is sufficient for him.", "At-Talaq", "65:3"),
        ("وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنتُمُ الْأَعْلَوْنَ إِن كُنتُم مُّؤْمِنِينَ", "Do not weaken or grieve — you are the superior, if you are believers.", "Al-Imran", "3:139"),
        ("الَّذِينَ يُنفِقُونَ أَمْوَالَهُم بِاللَّيْلِ وَالنَّهَارِ سِرًّا وَعَلَانِيَةً", "Those who spend in the way of Allah by night and day, secretly and publicly.", "Al-Baqarah", "2:274"),
        ("وَكَفَىٰ بِاللَّهِ وَكِيلًا", "Sufficient is Allah as Disposer of affairs.", "An-Nisa", "4:81"),
        ("وَاللَّهُ غَفُورٌ حَلِيمٌ", "Allah is Forgiving and Forbearing.", "Al-Baqarah", "2:225"),
        ("سَيَجْعَلُ اللَّهُ بَعْدَ عُسْرٍ يُسْرًا", "Allah will bring about, after hardship, ease.", "At-Talaq", "65:7"),
    ],

    "heartbroken": [
        ("وَبَشِّرِ الصَّابِرِينَ", "Give good tidings to the patient.", "Al-Baqarah", "2:155"),
        ("الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ", "Who, when struck by calamity, say: Indeed we belong to Allah, and to Him we shall return.", "Al-Baqarah", "2:156"),
        ("أُولَٰئِكَ عَلَيْهِمْ صَلَوَاتٌ مِّن رَّبِّهِمْ وَرَحْمَةٌ", "Upon them are blessings from their Lord and mercy.", "Al-Baqarah", "2:157"),
        ("وَأُولَٰئِكَ هُمُ الْمُهْتَدُونَ", "And it is those who are rightly guided.", "Al-Baqarah", "2:157"),
        ("إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ", "I only complain of my suffering and grief to Allah.", "Yusuf", "12:86"),
        ("وَاصْبِرْ وَمَا صَبْرُكَ إِلَّا بِاللَّهِ", "Be patient, and your patience is only by Allah.", "An-Nahl", "16:127"),
        ("وَلَا تَحْزَنْ عَلَيْهِمْ ۖ وَلَا تَكُ فِي ضَيْقٍ مِّمَّا يَمْكُرُونَ", "Do not grieve over them, nor be in distress over what they conspire.", "An-Nahl", "16:127"),
        ("لَا تَخَفْ وَلَا تَحْزَنْ", "Do not fear and do not grieve.", "Al-Ankabut", "29:33"),
        ("وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً", "He placed between you affection and mercy.", "Ar-Rum", "30:21"),
        ("ذَٰلِكَ يَوْمُ التَّغَابُنِ", "That will be the Day of Mutual Disillusion.", "At-Taghabun", "64:9"),
        ("وَالَّذِينَ هَاجَرُوا فِي اللَّهِ مِن بَعْدِ مَا ظُلِمُوا لَنُبَوِّئَنَّهُمْ", "Those who emigrate for the cause of Allah after being wronged — We will surely settle them.", "An-Nahl", "16:41"),
        ("سَلَامٌ عَلَيْكُم بِمَا صَبَرْتُمْ", "Peace be upon you for what you patiently endured.", "Ar-Ra'd", "13:24"),
        ("فَنِعْمَ عُقْبَى الدَّارِ", "How excellent is the final home.", "Ar-Ra'd", "13:24"),
        ("وَلَا تَهِنُوا فِي ابْتِغَاءِ الْقَوْمِ", "Do not weaken in the pursuit of the people.", "An-Nisa", "4:104"),
        ("إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", "Allah is with the patient.", "Al-Baqarah", "2:153"),
        ("وَلَنَجْزِيَنَّ الَّذِينَ صَبَرُوا أَجْرَهُم بِأَحْسَنِ مَا كَانُوا يَعْمَلُونَ", "We will surely give the patient their reward according to the best of what they used to do.", "An-Nahl", "16:96"),
        ("فَإِنَّ مَعَ الْعُسْرِ يُسْرًا", "With hardship will be ease.", "Al-Inshirah", "94:5"),
        ("لَتُبْلَوُنَّ فِي أَمْوَالِكُمْ وَأَنفُسِكُمْ", "You will surely be tested in your possessions and yourselves.", "Al-Imran", "3:186"),
        ("وَلَنَبْلُوَنَّكُم حَتَّىٰ نَعْلَمَ الْمُجَاهِدِينَ مِنكُمْ وَالصَّابِرِينَ", "We will surely test you until We make evident those who strive and the patient.", "Muhammad", "47:31"),
        ("قَالَ إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ وَأَعْلَمُ مِنَ اللَّهِ مَا لَا تَعْلَمُونَ", "He said: I only complain of my suffering and grief to Allah, and I know from Allah what you do not know.", "Yusuf", "12:86"),
        ("وَكَانَ فَضْلُ اللَّهِ عَلَيْكَ عَظِيمًا", "And the favor of Allah upon you has ever been great.", "An-Nisa", "4:113"),
    ],

    "lonely": [
        ("وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ", "And He is with you wherever you are.", "Al-Hadid", "57:4"),
        ("وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ", "We are closer to him than his jugular vein.", "Qaf", "50:16"),
        ("إِنَّ اللَّهَ مَعَنَا", "Indeed, Allah is with us.", "At-Tawbah", "9:40"),
        ("إِذْ يَقُولُ لِصَاحِبِهِ لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا", "When he said to his companion: do not grieve, indeed Allah is with us.", "At-Tawbah", "9:40"),
        ("إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ", "Indeed, with me is my Lord — He will guide me.", "Ash-Shu'ara", "26:62"),
        ("وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ", "When My servants ask you about Me — indeed, I am near.", "Al-Baqarah", "2:186"),
        ("أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ", "I respond to the supplication of the supplicant when he calls upon Me.", "Al-Baqarah", "2:186"),
        ("سَيَجْعَلُ لَهُمُ الرَّحْمَٰنُ وُدًّا", "The Most Merciful will appoint for them affection.", "Maryam", "19:96"),
        ("أَلَا إِنَّ أَوْلِيَاءَ اللَّهِ لَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ", "Unquestionably, for the allies of Allah there will be no fear concerning them, nor will they grieve.", "Yunus", "10:62"),
        ("إِنَّ وَلِيِّيَ اللَّهُ الَّذِي نَزَّلَ الْكِتَابَ", "Indeed, my protector is Allah, who has sent down the Book.", "Al-A'raf", "7:196"),
        ("اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا", "Allah is the ally of those who believe.", "Al-Baqarah", "2:257"),
        ("وَكَفَىٰ بِاللَّهِ وَلِيًّا وَكَفَىٰ بِاللَّهِ نَصِيرًا", "Sufficient is Allah as an Ally, and sufficient is Allah as a Helper.", "An-Nisa", "4:45"),
        ("وَكَفَىٰ بِرَبِّكَ هَادِيًا وَنَصِيرًا", "Sufficient is your Lord as a guide and a helper.", "Al-Furqan", "25:31"),
        ("هُوَ الَّذِي يُصَلِّي عَلَيْكُمْ وَمَلَائِكَتُهُ لِيُخْرِجَكُم مِّنَ الظُّلُمَاتِ إِلَى النُّورِ", "He is the One who confers blessing upon you, and His angels, that He may bring you out of darkness into light.", "Al-Ahzab", "33:43"),
        ("وَكَانَ بِالْمُؤْمِنِينَ رَحِيمًا", "He is, to the believers, Merciful.", "Al-Ahzab", "33:43"),
        ("إِنَّ رَبِّي قَرِيبٌ مُّجِيبٌ", "Indeed, my Lord is near and responsive.", "Hud", "11:61"),
        ("وَإِن يَمْسَسْكَ اللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ إِلَّا هُوَ", "If Allah touches you with adversity, none can remove it but Him.", "Al-An'am", "6:17"),
        ("فَإِنِّي قَرِيبٌ ۖ أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ", "I am near — I respond to the supplicant when he calls upon Me.", "Al-Baqarah", "2:186"),
        ("لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا", "Do not grieve. Indeed, Allah is with us.", "At-Tawbah", "9:40"),
        ("ذَٰلِكَ بِأَنَّ اللَّهَ مَوْلَى الَّذِينَ آمَنُوا", "That is because Allah is the protector of those who believe.", "Muhammad", "47:11"),
        ("وَأَنَّ الْكَافِرِينَ لَا مَوْلَىٰ لَهُمْ", "And the disbelievers have no protector.", "Muhammad", "47:11"),
    ],
}

# ─────────── Daily rotating reminders (unchanged) ───────────
DAILY_REMINDERS = [
    {"text": "The best of you are those best to their families.", "source": "Prophet ﷺ — Tirmidhi"},
    {"text": "A kind word is charity.", "source": "Prophet ﷺ — Bukhari"},
    {"text": "The most beloved deeds to Allah are the most consistent, even if small.", "source": "Prophet ﷺ — Bukhari"},
    {"text": "Smiling at your brother is charity.", "source": "Prophet ﷺ — Tirmidhi"},
    {"text": "Make things easy and do not make them difficult.", "source": "Prophet ﷺ — Bukhari"},
    {"text": "None of you truly believes until he loves for his brother what he loves for himself.", "source": "Prophet ﷺ — Bukhari"},
    {"text": "Cleanliness is half of faith.", "source": "Prophet ﷺ — Muslim"},
    {"text": "Whoever believes in Allah and the Last Day, let him speak good or remain silent.", "source": "Prophet ﷺ — Bukhari"},
    {"text": "The strong is not the one who overcomes by his strength, but the one who controls himself when angry.", "source": "Prophet ﷺ — Bukhari"},
    {"text": "Actions are by intentions.", "source": "Prophet ﷺ — Bukhari"},
    {"text": "Verily, in the remembrance of Allah do hearts find rest.", "source": "Qur'an 13:28"},
    {"text": "Indeed, with hardship comes ease.", "source": "Qur'an 94:6"},
    {"text": "And He is with you wherever you are.", "source": "Qur'an 57:4"},
    {"text": "Your Lord has not abandoned you.", "source": "Qur'an 93:3"},
    {"text": "Do not despair of the mercy of Allah.", "source": "Qur'an 39:53"},
    {"text": "Whoever fears Allah, He will make for him a way out.", "source": "Qur'an 65:2"},
    {"text": "And whoever puts their trust in Allah — He is sufficient for them.", "source": "Qur'an 65:3"},
    {"text": "Allah loves those who are constantly repentant.", "source": "Qur'an 2:222"},
    {"text": "The dearest of people to Allah are those most beneficial to others.", "source": "Prophet ﷺ — al-Mu'jam al-Awsat"},
    {"text": "Whoever conceals a Muslim's faults, Allah will conceal his on the Day of Judgment.", "source": "Prophet ﷺ — Muslim"},
]

# ─────────── Adhkar — full Hisn al-Muslim text ───────────
AYAT_AL_KURSI = "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ"
SURAH_IKHLAS = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۞ قُلْ هُوَ اللَّهُ أَحَدٌ ۞ اللَّهُ الصَّمَدُ ۞ لَمْ يَلِدْ وَلَمْ يُولَدْ ۞ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ"
SURAH_FALAQ = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۞ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۞ مِن شَرِّ مَا خَلَقَ ۞ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۞ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۞ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ"
SURAH_NAS = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۞ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۞ مَلِكِ النَّاسِ ۞ إِلَٰهِ النَّاسِ ۞ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۞ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۞ مِنَ الْجِنَّةِ وَالنَّاسِ"
SAYYID_ISTIGHFAR = "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ"
LAST_TWO_BAQARAH = "آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ ۞ لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ۖ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ۚ أَنتَ مَوْلَانَا فَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ"

AZKAR_SECTIONS = [
    {
        "id": "morning",
        "title_en": "Morning Adhkar",
        "title_ar": "أذكار الصباح",
        "items": [
            {"arabic": AYAT_AL_KURSI, "transliteration": "Allahu la ilaha illa Huwa al-Hayyul-Qayyum…",
             "english": "Ayat al-Kursi (2:255). Whoever recites it in the morning is protected from jinn until evening.", "count": 1},
            {"arabic": SURAH_IKHLAS, "transliteration": "Qul Huwa Allahu Ahad…",
             "english": "Surah Al-Ikhlas (112) — three times.", "count": 3},
            {"arabic": SURAH_FALAQ, "transliteration": "Qul a'oodhu bi-Rabbil-falaq…",
             "english": "Surah Al-Falaq (113) — three times.", "count": 3},
            {"arabic": SURAH_NAS, "transliteration": "Qul a'oodhu bi-Rabbin-nas…",
             "english": "Surah An-Nas (114) — three times.", "count": 3},
            {"arabic": "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَٰذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَٰذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ",
             "transliteration": "Asbahna wa asbaha al-mulku lillah…",
             "english": "We have reached the morning, and all sovereignty belongs to Allah. My Lord, I ask You for the good of this day and what follows it; I seek refuge in You from the evil of this day and what follows it.", "count": 1},
            {"arabic": "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ",
             "transliteration": "Allahumma bika asbahna, wa bika amsayna…",
             "english": "O Allah, by You we enter the morning, by You the evening; by You we live and die, and to You is the resurrection.", "count": 1},
            {"arabic": SAYYID_ISTIGHFAR, "transliteration": "Allahumma anta Rabbi la ilaha illa anta…",
             "english": "Sayyid al-Istighfar. Whoever says it in the morning with certainty and dies that day enters Paradise.", "count": 1},
            {"arabic": "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَٰهَ إِلَّا أَنْتَ",
             "transliteration": "Allahumma 'afini fi badani…",
             "english": "O Allah, grant me well-being in my body, hearing, and sight. There is no god but You.", "count": 3},
            {"arabic": "حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
             "transliteration": "Hasbiyallahu la ilaha illa Huwa…",
             "english": "Allah is sufficient for me. None has the right to be worshipped but Him. On Him I rely.", "count": 7},
            {"arabic": "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ",
             "transliteration": "Bismillahil-ladhi la yadurru ma'asmihi shay'…",
             "english": "In the name of Allah, with whose name nothing on earth or in the heavens can cause harm.", "count": 3},
            {"arabic": "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا",
             "transliteration": "Radeetu billahi Rabba…",
             "english": "I am pleased with Allah as my Lord, Islam as my religion, and Muhammad ﷺ as my Prophet.", "count": 3},
            {"arabic": "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَىٰ نَفْسِي طَرْفَةَ عَيْنٍ",
             "transliteration": "Ya Hayyu ya Qayyum…",
             "english": "O Ever-Living, O Sustainer — by Your mercy I seek aid. Rectify all my affairs and do not leave me to myself for the blink of an eye.", "count": 1},
            {"arabic": "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", "transliteration": "SubhanAllahi wa bihamdihi",
             "english": "Glory and praise to Allah. (100x — sins forgiven though they be like sea foam.)", "count": 100},
            {"arabic": "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
             "transliteration": "La ilaha illa Allah wahdahu la sharika lah…",
             "english": "There is no god but Allah alone. (10x — protection from Shaytan until evening.)", "count": 10},
            {"arabic": "اللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَىٰ نَبِيِّنَا مُحَمَّدٍ",
             "transliteration": "Allahumma salli wa sallim wa barik 'ala nabiyyina Muhammad",
             "english": "O Allah, send prayers, peace, and blessings upon our Prophet Muhammad.", "count": 10},
        ],
    },
    {
        "id": "evening",
        "title_en": "Evening Adhkar",
        "title_ar": "أذكار المساء",
        "items": [
            {"arabic": AYAT_AL_KURSI, "transliteration": "Ayat al-Kursi (2:255)",
             "english": "Whoever recites it in the evening is protected from jinn until morning.", "count": 1},
            {"arabic": SURAH_IKHLAS, "transliteration": "Surah Al-Ikhlas",
             "english": "Surah Al-Ikhlas — three times.", "count": 3},
            {"arabic": SURAH_FALAQ, "transliteration": "Surah Al-Falaq",
             "english": "Surah Al-Falaq — three times.", "count": 3},
            {"arabic": SURAH_NAS, "transliteration": "Surah An-Nas",
             "english": "Surah An-Nas — three times.", "count": 3},
            {"arabic": "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَٰذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا",
             "transliteration": "Amsayna wa amsa al-mulku lillah…",
             "english": "We have reached the evening… My Lord, I ask You for the good of this night and what follows.", "count": 1},
            {"arabic": "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ",
             "transliteration": "Allahumma bika amsayna…",
             "english": "O Allah, by You we enter evening and morning…", "count": 1},
            {"arabic": SAYYID_ISTIGHFAR, "transliteration": "Sayyid al-Istighfar",
             "english": "Whoever says it in the evening with certainty and dies that night enters Paradise.", "count": 1},
            {"arabic": "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
             "transliteration": "A'oodhu bi-kalimatillahit-tammati min sharri ma khalaq",
             "english": "I seek refuge in the perfect words of Allah from the evil of what He has created.", "count": 3},
            {"arabic": "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ",
             "transliteration": "Bismillahil-ladhi la yadurru…",
             "english": "In the name of Allah — nothing in the heavens or earth can harm with His name.", "count": 3},
            {"arabic": "حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
             "transliteration": "Hasbiyallahu la ilaha illa Huwa…",
             "english": "Allah is sufficient for me. On Him I rely.", "count": 7},
            {"arabic": "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا",
             "transliteration": "Radeetu billahi Rabba…",
             "english": "I am pleased with Allah as Lord, Islam as religion, Muhammad ﷺ as Prophet.", "count": 3},
            {"arabic": "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", "transliteration": "SubhanAllahi wa bihamdihi",
             "english": "Glory and praise to Allah. (100x)", "count": 100},
            {"arabic": "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ", "transliteration": "Astaghfirullaha wa atoobu ilayh",
             "english": "I seek Allah's forgiveness and turn to Him in repentance.", "count": 100},
            {"arabic": "اللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَىٰ نَبِيِّنَا مُحَمَّدٍ",
             "transliteration": "Allahumma salli wa sallim wa barik 'ala nabiyyina Muhammad",
             "english": "O Allah, send prayers, peace, and blessings upon our Prophet Muhammad. (10x)", "count": 10},
        ],
    },
    {
        "id": "after_prayer",
        "title_en": "After Prayer",
        "title_ar": "أذكار بعد الصلاة",
        "items": [
            {"arabic": "أَسْتَغْفِرُ اللَّهَ", "transliteration": "Astaghfirullah",
             "english": "I seek Allah's forgiveness. (3x immediately after the salam.)", "count": 3},
            {"arabic": "اللَّهُمَّ أَنْتَ السَّلَامُ، وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
             "transliteration": "Allahumma antas-Salam…",
             "english": "O Allah, You are Peace, and from You is peace. Blessed are You, Possessor of Majesty and Honor.", "count": 1},
            {"arabic": "سُبْحَانَ اللَّهِ", "transliteration": "SubhanAllah",
             "english": "Glory is to Allah.", "count": 33},
            {"arabic": "الْحَمْدُ لِلَّهِ", "transliteration": "Alhamdulillah",
             "english": "All praise is to Allah.", "count": 33},
            {"arabic": "اللَّهُ أَكْبَرُ", "transliteration": "Allahu Akbar",
             "english": "Allah is the Greatest.", "count": 34},
            {"arabic": "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
             "transliteration": "La ilaha illa Allah wahdahu la sharika lah…",
             "english": "There is no god but Allah alone, after completing the tasbeeh.", "count": 1},
            {"arabic": AYAT_AL_KURSI, "transliteration": "Ayat al-Kursi",
             "english": "Whoever recites Ayat al-Kursi after every obligatory prayer — nothing keeps him from Paradise except death.", "count": 1},
            {"arabic": "اللَّهُمَّ أَعِنِّي عَلَىٰ ذِكْرِكَ، وَشُكْرِكَ، وَحُسْنِ عِبَادَتِكَ",
             "transliteration": "Allahumma a'inni 'ala dhikrika…",
             "english": "O Allah, help me to remember You, thank You, and worship You in the best manner.", "count": 1},
        ],
    },
    {
        "id": "sleep",
        "title_en": "Before Sleep",
        "title_ar": "أذكار النوم",
        "items": [
            {"arabic": "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", "transliteration": "Bismika Allahumma amootu wa ahya",
             "english": "In Your name, O Allah, I die and I live.", "count": 1},
            {"arabic": AYAT_AL_KURSI, "transliteration": "Ayat al-Kursi (2:255)",
             "english": "A guardian from Allah remains with you and no devil comes near until morning.", "count": 1},
            {"arabic": SURAH_IKHLAS, "transliteration": "Surah Al-Ikhlas",
             "english": "Recite into your palms (then blow into them and wipe over your body).", "count": 3},
            {"arabic": SURAH_FALAQ, "transliteration": "Surah Al-Falaq",
             "english": "Recite into your palms.", "count": 3},
            {"arabic": SURAH_NAS, "transliteration": "Surah An-Nas",
             "english": "Recite into your palms. Blow into them and wipe over the body — three times.", "count": 3},
            {"arabic": LAST_TWO_BAQARAH, "transliteration": "Amanar-rasoolu… (2:285-286)",
             "english": "Last two verses of Al-Baqarah. Whoever recites them at night, they will suffice him.", "count": 1},
            {"arabic": "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
             "transliteration": "Allahumma qini 'adhabaka…",
             "english": "O Allah, save me from Your punishment on the Day You resurrect Your servants. (Place hand under cheek.)", "count": 3},
            {"arabic": "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْحَيَّ الْقَيُّومَ وَأَتُوبُ إِلَيْهِ",
             "transliteration": "Astaghfirullah al-'Adheem…",
             "english": "I seek the forgiveness of Allah, the Most Great, and turn to Him in repentance.", "count": 3},
        ],
    },
    {
        "id": "daily",
        "title_en": "Daily Duas",
        "title_ar": "أدعية يومية",
        "items": [
            {"arabic": "بِسْمِ اللَّهِ", "transliteration": "Bismillah",
             "english": "In the name of Allah. (Before eating, drinking, or beginning anything.)", "count": 1},
            {"arabic": "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَٰذَا، وَرَزَقَنِيهِ، مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
             "transliteration": "Alhamdulillah alladhi at'amani hadha…",
             "english": "Praise be to Allah who fed me this and provided it for me. (After eating — past sins forgiven.)", "count": 1},
            {"arabic": "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
             "transliteration": "Bismillah, tawakkaltu 'ala Allah…",
             "english": "In the name of Allah, I rely on Allah; there is no might nor power except with Allah. (Leaving home.)", "count": 1},
            {"arabic": "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ، وَخَيْرَ الْمَخْرَجِ، بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا",
             "transliteration": "Allahumma inni as'aluka khayral-mawliji…",
             "english": "O Allah, I ask You for the best of entries and exits. In Allah's name we enter, in Allah's name we leave.", "count": 1},
            {"arabic": "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ، وَغَلَبَةِ الرِّجَالِ",
             "transliteration": "Allahumma inni a'oodhu bika min al-hammi wal-hazan…",
             "english": "O Allah, I seek refuge in You from anxiety and sorrow, weakness and laziness, miserliness and cowardice, the burden of debt, and being overpowered.", "count": 1},
            {"arabic": "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
             "transliteration": "Rabbana atina fid-dunya hasanah…",
             "english": "Our Lord, grant us good in this world and the Hereafter, and protect us from the Fire. (2:201)", "count": 1},
        ],
    },
]
