"""Sunnah Compendium — curated from Hisn al-Muslim, Riyad as-Salihin, Sahih Bukhari/Muslim."""

SUNNAH_CATEGORIES = [
    {"id": "purity",     "title": "Purity & Wudu",        "subtitle": "Tahara",          "monogram": "ط"},
    {"id": "worship",    "title": "Worship & Salah",      "subtitle": "Ibadah",          "monogram": "ع"},
    {"id": "food_drink", "title": "Food & Drink",         "subtitle": "Ta'am",           "monogram": "ط"},
    {"id": "sleep",      "title": "Sleep & Waking",       "subtitle": "Nawm",            "monogram": "ن"},
    {"id": "home",       "title": "Home & Household",     "subtitle": "Bayt",            "monogram": "ب"},
    {"id": "conduct",    "title": "Public Conduct",       "subtitle": "Akhlaq",          "monogram": "خ"},
    {"id": "speech",     "title": "Speech & Tongue",      "subtitle": "Lisan",           "monogram": "ل"},
    {"id": "business",   "title": "Business & Wealth",    "subtitle": "Mu'amalat",       "monogram": "م"},
    {"id": "travel",     "title": "Travel",               "subtitle": "Safar",           "monogram": "س"},
    {"id": "grooming",   "title": "Dress & Grooming",     "subtitle": "Libas",           "monogram": "ز"},
    {"id": "marriage",   "title": "Marital Intimacy",     "subtitle": "Nikah",           "monogram": "ن"},
    {"id": "other",      "title": "Daily Threads",        "subtitle": "Yawmiyyat",       "monogram": "ي"},
]

# Full sunnah list — each entry has stable id
def _s(idx, title, category, trigger, rarity, hadith_text, hadith_source, why_ordained, demographic="general", time_hint=None):
    return {
        "id": f"s-{idx:03d}",
        "title": title,
        "category": category,
        "trigger": trigger,
        "rarity": rarity,
        "hadith_text": hadith_text,
        "hadith_source": hadith_source,
        "why_ordained": why_ordained,
        "demographic": demographic,
        "time_hint": time_hint,  # e.g. "after_fajr", "before_sleep", "qailulah", "friday_morning", null
    }

SUNNAHS = [
    _s(1, "Entering the bathroom with the left foot", "purity", "Approaching the bathroom", "highly_forgotten",
       "The Prophet ﷺ preferred the right side for noble matters and the left for removing impurities.",
       "Sahih al-Bukhari 168",
       "A physical mindfulness — segregating honorable actions from those involving impurity. The body remembers what the heart forgets."),
    _s(2, "Dua before entering the bathroom", "purity", "Bathroom door detected", "common",
       "O Allah, I seek refuge in You from male and female devils — Allahumma inni a'oodhu bika minal-khubthi wal-khaba'ith.",
       "Sahih al-Bukhari 142",
       "Divine protection during the most vulnerable and impure physical state."),
    _s(3, "Leaving the bathroom with the right foot", "purity", "Exiting the bathroom", "highly_forgotten",
       "Derived from the Prophet's ﷺ consistent preference for the right side in all noble actions.",
       "Sahih al-Bukhari 168", "A transition gesture — from a state of impurity back into ordinary life."),
    _s(4, "Saying Ghufranak after leaving the bathroom", "purity", "After leaving the bathroom", "highly_forgotten",
       "When the Prophet ﷺ came out of the toilet he would say: Ghufranak — Your forgiveness.",
       "Jami' at-Tirmidhi 7",
       "Reconnect the heart with Allah immediately after a necessary silence."),
    _s(5, "Miswak before wudu", "purity", "Beginning wudu", "highly_forgotten",
       "Were it not difficult for my Ummah, I would have ordered them to use the Miswak before every prayer.",
       "Sahih al-Bukhari 887", "Oral purity before conversing with the Creator.", "general", "before_each_salah"),
    _s(6, "Use little water in wudu", "purity", "During wudu", "highly_forgotten",
       "The Prophet ﷺ performed wudu with approximately one mudd (a single handful) of water.",
       "Sahih Muslim 325", "Stewardship of the earth and a stand against wastefulness (israf)."),
    _s(7, "Morning Adhkar after Fajr", "worship", "15 minutes after Fajr", "highly_forgotten",
       "The Prophet ﷺ consistently recited the morning remembrances.",
       "Abu Dawud 5072",
       "Set the spiritual trajectory of the day — a fortress against anxiety and harm.", "general", "after_fajr"),
    _s(8, "Evening Adhkar after Asr", "worship", "Between Asr and Maghrib", "highly_forgotten",
       "The Prophet ﷺ consistently recited the evening remembrances.",
       "Abu Dawud 5072", "Clear the spiritual residue of the day's worldly interactions.", "general", "asr_to_maghrib"),
    _s(9, "Ayat al-Kursi before sleep", "sleep", "Bedtime", "common",
       "Allah will appoint a guardian over you, and Shaytan will not approach you until morning.",
       "Sahih al-Bukhari 2311", "Absolute nighttime protection during the vulnerability of sleep.", "general", "before_sleep"),
    _s(10, "Recite Surah al-Mulk before sleep", "sleep", "Before sleep", "highly_forgotten",
       "It intercedes for its companion until he is forgiven.",
       "Tirmidhi 2891", "A nightly defense against the trials of the grave.", "general", "before_sleep"),
    _s(11, "Qailulah — the midday rest", "sleep", "Around Dhuhr", "highly_forgotten",
       "Take a brief siesta, for the devils do not take siestas.",
       "Sahih al-Jami' 4431",
       "A short rest that fuels night worship — the Prophet's ﷺ rhythm for sustainable devotion.", "general", "qailulah"),
    _s(12, "Tahajjud in the last third of the night", "worship", "Last third of the night", "highly_forgotten",
       "Our Lord descends to the nearest heaven in the last third of the night and says: Who is calling Me, that I may answer him?",
       "Sahih al-Bukhari 1145",
       "The quietest hour. The conversation Allah Himself initiates.", "general", "last_third"),
    _s(13, "Two rak'ah after wudu", "worship", "Just after wudu", "highly_forgotten",
       "Whoever performs wudu like this and then prays two rak'ah, his past sins will be forgiven.",
       "Sahih al-Bukhari 159", "Lock in the spiritual state immediately while the soul is still clean."),
    _s(14, "Sleeping on the right side in wudu", "sleep", "Before sleeping", "common",
       "When you go to your bed, perform wudu as you would for prayer, then lie down on your right side.",
       "Sahih al-Bukhari 247",
       "Meet the angel of sleep in a state of purity — and possibly meet death itself in purity.", "general", "before_sleep"),
    _s(15, "Dua upon waking", "sleep", "Upon waking", "common",
       "Alhamdu lillah alladhi ahyana ba'da ma amatana wa ilayhin-nushoor.",
       "Sahih al-Bukhari 6312",
       "Gratitude for being given life back — and a reminder of the ultimate return.", "general", "on_wake"),
    _s(16, "Bismillah before eating", "food_drink", "Meal times", "common",
       "When any of you eats, let him say Bismillah; if he forgets at the beginning, let him say Bismillahi awwalahu wa akhirah.",
       "Tirmidhi 1858", "Acknowledge that the food is His before it is yours."),
    _s(17, "Eat with three fingers", "food_drink", "Meal times", "highly_forgotten",
       "The Prophet ﷺ used to eat with three fingers, and would lick them before wiping them.",
       "Sahih Muslim 2032", "A small constraint that breeds presence — modest, deliberate, dignified."),
    _s(18, "Drinking water in three breaths", "food_drink", "Drinking", "highly_forgotten",
       "The Prophet ﷺ used to take three breaths while drinking — saying it was more wholesome and quenching.",
       "Sahih al-Bukhari 5631", "Honor the body's rhythm — and remember that even water is a gift to be tasted."),
    _s(19, "Sitting while drinking", "food_drink", "Drinking", "highly_forgotten",
       "The Prophet ﷺ forbade drinking while standing.",
       "Sahih Muslim 2024", "Slow the moment. Receive the blessing with dignity."),
    _s(20, "Praise Allah after the meal", "food_drink", "After meals", "common",
       "Allah is pleased with a servant who eats something and praises Him for it, or drinks and praises Him for it.",
       "Sahih Muslim 2734", "Lock the blessing in with gratitude — and you will see it again."),
    _s(21, "Covering food and drink overnight", "food_drink", "Storing food", "highly_forgotten",
       "Cover the vessel and tie the waterskin; for there is a night in the year when an affliction descends and finds nothing covered, except that some of it enters.",
       "Sahih Muslim 2014", "Practical baraka — caring for one's provision out of trust and humility.", "household"),
    _s(22, "Dua entering the home", "home", "Entering the home", "common",
       "Allahumma inni as'aluka khayral-mawliji wa khayral-makhraji; bismillahi walajna, wa bismillahi kharajna, wa 'ala Rabbina tawakkalna.",
       "Abu Dawud 5096", "Place the threshold — and everyone inside — under His name.", "household"),
    _s(23, "Greet the household with Salam", "home", "Entering the home", "common",
       "When you enter your home, greet your family with Salam — it will be a blessing for you and them.",
       "Tirmidhi 2698", "Carry peace through the door before you carry anything else.", "household"),
    _s(24, "Two rak'ah before leaving home", "travel", "Leaving home/city", "highly_forgotten",
       "The Prophet ﷺ would pray two rak'ah before setting out on a journey.",
       "Tabarani", "Place the journey under His custody from the first step.", "general", "before_travel"),
    _s(25, "Travel dua", "travel", "Starting a journey", "common",
       "Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrineen, wa inna ila Rabbina la-munqaliboon.",
       "Sahih Muslim 1342", "Recognize the gift of motion — and the inevitability of the return."),
    _s(26, "Visit the masjid first upon return", "travel", "Returning to home city", "highly_forgotten",
       "Whenever the Prophet ﷺ returned from a journey, he would go to the mosque first and pray two rak'ah.",
       "Sahih al-Bukhari 3088", "Begin the homecoming with Him — He brought you back."),
    _s(27, "Hide the good deed", "conduct", "Giving charity", "highly_forgotten",
       "Seven will be shaded by Allah on the Day no shade exists but His — among them: a man who gives charity so secretly that his left hand does not know what his right hand has given.",
       "Sahih al-Bukhari 1423", "Annihilate the ego. Protect the deed from being eaten by the eye."),
    _s(28, "Silence when angry", "speech", "Heated debate", "highly_forgotten",
       "If one of you becomes angry, let him be silent.",
       "Musnad Ahmad 2136", "Silence is the emergency brake the tongue forgot it had."),
    _s(29, "Look at those below you", "conduct", "Scrolling, comparison", "highly_forgotten",
       "Look at those who are beneath you and do not look at those who are above you — it is more fitting that you do not belittle the favor of Allah upon you.",
       "Sahih Muslim 2963", "The cure for the modern disease of comparison."),
    _s(30, "Smile — it is charity", "conduct", "Greeting another", "common",
       "Your smiling in the face of your brother is charity.",
       "Tirmidhi 1956", "The smallest light, freely given."),
    _s(31, "Be kind to your neighbor", "conduct", "Interacting with neighbors", "common",
       "Jibril kept recommending me to be kind to the neighbor, until I thought he would make him an heir.",
       "Sahih al-Bukhari 6014", "The closest stranger Allah placed in your life. Begin there.", "public"),
    _s(32, "Exchange gifts", "conduct", "Social bonds", "common",
       "Exchange gifts — you will love each other.",
       "Al-Adab al-Mufrad 594", "Small generosities are the threads that hold communities together."),
    _s(33, "Ihsan (excellence) in work", "business", "Beginning a task", "common",
       "Allah loves that when one of you does a task, he perfects it.",
       "Al-Bayhaqi, Shu'ab al-Iman 5313",
       "Excellence is the visible form of sincerity. Your craft is a window onto your worship.", "work"),
    _s(34, "Take advantage of five before five", "other", "Reviewing the day", "highly_forgotten",
       "Take advantage of five before five: your youth before your old age, your health before your illness, your wealth before your poverty, your free time before your busyness, and your life before your death.",
       "Al-Hakim, al-Mustadrak 7846", "Time is the only capital that does not return.", "general"),
    _s(35, "Wear the right side first", "grooming", "Dressing", "common",
       "The Prophet ﷺ liked to begin with the right when putting on shoes, combing his hair, purifying himself, and in all his affairs.",
       "Sahih al-Bukhari 5854", "The body's small grammar of intention."),
    _s(36, "Comb the hair every other day", "grooming", "Grooming", "highly_forgotten",
       "The Prophet ﷺ forbade combing the hair except every other day.",
       "Nasa'i 5055, Abu Dawud 4159", "A balance between neglect and excessive self-adornment."),
    _s(37, "Apply itr/perfume on Fridays", "grooming", "Friday morning", "common",
       "Ghusl on Friday is obligatory upon every adult, along with miswak and applying perfume if available.",
       "Sahih Muslim 846", "Honor the gathering of the believers — meet them clean and fragrant.", "general", "friday_morning"),
    _s(38, "Trim nails, mustache, armpit and pubic hair", "grooming", "Every 40 days at most", "common",
       "The Prophet ﷺ set for us a limit of no more than forty nights for trimming the mustache, clipping the nails, plucking the armpit hair, and shaving the pubic hair.",
       "Sahih Muslim 258", "The body's regular maintenance is part of the deen."),
    _s(39, "Surah al-Kahf on Friday", "worship", "Thursday night / Friday", "highly_forgotten",
       "Whoever recites Surah al-Kahf on Friday, a light will shine for him between the two Fridays.",
       "Al-Hakim 3392 (sahih)",
       "A weekly anchor of meaning — and a defense against the great trial of the Dajjal.", "general", "friday_morning"),
    _s(40, "Salah al-Duha (forenoon prayer)", "worship", "After sunrise, before Dhuhr", "highly_forgotten",
       "In the morning, charity is due upon every joint of the human body — and two rak'ah of Duha suffice for all of that.",
       "Sahih Muslim 720", "Pay the daily zakah owed by the body that woke up alive.", "general", "duha"),
    _s(41, "Visit a sick person", "conduct", "Visiting the sick", "highly_forgotten",
       "Whoever visits a sick person sits in the gardens of mercy until he returns.",
       "Sahih Muslim 2568", "Mercy descends on those who sit in the room of suffering.", "public"),
    # ── Marriage & household demographic ──
    _s(42, "Pray two rak'ah together with your spouse", "marriage", "Tahajjud / quiet evening", "highly_forgotten",
       "May Allah have mercy on a man who gets up at night, prays, and wakes his wife. If she refuses, he sprinkles water on her face — and on a woman who does likewise.",
       "Abu Dawud 1308", "Worship done as a pair is woven into the very fabric of the home.", "married"),
    _s(43, "Dua before intimacy", "marriage", "Before relations", "common",
       "Bismillah, Allahumma jannibna ash-shaytan, wa jannib ash-shaytan ma razaqtana.",
       "Sahih al-Bukhari 141",
       "Place even this private moment in His name — and protection extends to any child He grants.", "married"),
    _s(44, "Affection in greeting your spouse", "marriage", "Returning home", "highly_forgotten",
       "The Prophet ﷺ would always smile when he saw Aisha, and she described him as the most affectionate of people in his home.",
       "Tirmidhi 3895", "The home that is greeted with light needs little else.", "married"),
    _s(45, "Eating together from one plate", "marriage", "Meal times together", "highly_forgotten",
       "Eat together and not separately, for the blessing is in the company.",
       "Ibn Majah 3286", "Baraka multiplies where two hands break bread from the same dish.", "married"),
    _s(46, "Drink from the spot the other drank from", "marriage", "Drinking with spouse", "highly_forgotten",
       "Aisha (ra) said: I would drink and pass the vessel to the Prophet ﷺ — he would place his mouth where mine had been.",
       "Sahih Muslim 300", "The smallest physical gesture can carry a vast amount of love.", "married"),
    _s(47, "Speak well of your spouse to others", "marriage", "In conversation", "highly_forgotten",
       "The most perfect of believers in faith are those best in character — and the best of you are those best to their families.",
       "Tirmidhi 1162", "Your tongue can either build or burn the home you sleep in.", "married"),
    _s(48, "Be the first to forgive at home", "marriage", "After a disagreement", "highly_forgotten",
       "The best of you are the best to your wives — and I am the best of you to my wife.",
       "Tirmidhi 3895", "Love is rarely lost in one large blow — it leaks slowly through unforgiven small things.", "married"),
    # ── Men / Women specific (a few each) ──
    _s(49, "Pray in congregation at the masjid", "worship", "Each obligatory prayer", "common",
       "Prayer in congregation is twenty-seven times better than prayer alone.",
       "Sahih al-Bukhari 645", "Worship is built strongest in shoulder-to-shoulder rows.", "men"),
    _s(50, "Pray in the inner part of the home", "worship", "Each obligatory prayer", "highly_forgotten",
       "The prayer of a woman in the innermost part of her house is better than her prayer in her courtyard.",
       "Abu Dawud 570", "Honor — and ease — is found in the quiet space she chooses for Him.", "women"),
    _s(51, "Hijab as a fortress of dignity", "grooming", "Stepping out", "common",
       "O Prophet, tell your wives and daughters and the believing women to draw their cloaks over themselves — that is more suitable that they will be known and not be abused.",
       "Qur'an 33:59", "What you wear becomes a sentence the world reads about you.", "women"),
    _s(52, "Lower the gaze", "conduct", "In public spaces", "common",
       "Tell the believing men to lower their gaze and guard their modesty.",
       "Qur'an 24:30", "The eye is a door — guard it and the heart stays your own.", "men"),
    _s(53, "Honor your mother three times before your father", "conduct", "Calling parents", "highly_forgotten",
       "A man asked: who is most deserving of my companionship? He ﷺ said: Your mother. He said: Then who? He said: Your mother. He said: Then who? He said: Your mother. He said: Then who? He said: Your father.",
       "Sahih al-Bukhari 5971", "The deepest debt — and the easiest one to forget the size of.", "general"),
    _s(54, "Send salah upon the Prophet ﷺ often", "worship", "Throughout the day", "common",
       "Whoever sends one salah upon me, Allah sends ten upon him.",
       "Sahih Muslim 408", "A short phrase, an enormous response.", "general"),
    _s(55, "Greet children with Salam", "home", "Encountering children", "highly_forgotten",
       "The Prophet ﷺ passed by some children and greeted them with Salam.",
       "Sahih al-Bukhari 6247", "The smallest people deserve the same respect as the largest.", "household"),
    _s(56, "Anas's rule — never say 'uff' to parents", "conduct", "Caring for parents", "common",
       "And do not say to them so much as 'uff' — but speak to them a noble word.",
       "Qur'an 17:23", "The smallest sound of irritation, if directed at the right person, is forbidden.", "general"),
    _s(57, "Hasten to break the fast", "worship", "At Maghrib in Ramadan", "common",
       "The people will continue to be in goodness as long as they hasten to break the fast.",
       "Sahih al-Bukhari 1957", "Honor the moment with a date and water before anything else.", "general", "maghrib_ramadan"),
    _s(58, "Eat the suhoor — even a sip", "worship", "Before Fajr in Ramadan", "common",
       "Eat suhoor — for in suhoor there is barakah.",
       "Sahih al-Bukhari 1923", "Even a date and water carries blessing the body cannot measure.", "general", "before_fajr_ramadan"),
    _s(59, "Drink Zamzam standing facing the qibla", "food_drink", "When drinking Zamzam", "highly_forgotten",
       "Zamzam water is for whatever it is drunk for.",
       "Ibn Majah 3062", "A single exception to the rule of sitting — drink it with the purpose declared.", "general"),
    _s(60, "Hospitable for three days to a guest", "home", "Hosting a guest", "common",
       "Whoever believes in Allah and the Last Day, let him honor his guest — his obligatory honoring is one day and night, and hospitality is three days.",
       "Sahih al-Bukhari 6135", "The door opens — let it open generously.", "household"),
]


def sunnah_of_the_hour(now_hour: int) -> dict:
    """Pick a contextual sunnah based on local hour (0-23)."""
    # 04-07 morning adhkar after fajr
    if 4 <= now_hour < 8:
        return next((s for s in SUNNAHS if s["id"] == "s-007"), SUNNAHS[6])
    # 8-10 duha
    if 8 <= now_hour < 11:
        return next((s for s in SUNNAHS if s["id"] == "s-040"), SUNNAHS[39])
    # 11-13 qailulah
    if 11 <= now_hour < 14:
        return next((s for s in SUNNAHS if s["id"] == "s-011"), SUNNAHS[10])
    # 14-17 evening adhkar window starts approaching
    if 14 <= now_hour < 17:
        return next((s for s in SUNNAHS if s["id"] == "s-029"), SUNNAHS[28])
    # 17-19 evening adhkar between asr and maghrib
    if 17 <= now_hour < 20:
        return next((s for s in SUNNAHS if s["id"] == "s-008"), SUNNAHS[7])
    # 20-22 family/intimacy/home time
    if 20 <= now_hour < 23:
        return next((s for s in SUNNAHS if s["id"] == "s-023"), SUNNAHS[22])
    # 23-3 sleep & tahajjud
    if now_hour >= 23 or now_hour < 4:
        return next((s for s in SUNNAHS if s["id"] == "s-012"), SUNNAHS[11])
    return SUNNAHS[0]
